version: 1.1.0-{build}
pull_requests:
  do_not_increment_build_number: true
image: Visual Studio 2017

install:
- '"C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\Common7\Tools\VsDevCmd.bat"'
- msbuild Source\Solutions\Bifrost_All.sln /t:restore

build_script:
- cmd: .\build.cmd All
test:
  assemblies: 'Source\**\*.Specs.dll'
deploy: off
artifacts:
- path: artifacts\nuget\*
  name: nuget
